### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by GiedriusS** [pingcap/dead-mans-switch#8]
Hello, thanks for this software! I have noticed that this repository has no license. Could you please provide one (add a file called LICENSE to the repository) because otherwise no one can re-use your project, modify it, or do anything with it (https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license)? @zjj2wry @qiffang thanks in advance :hugs:

**Comment by tennix** [comment]
@GiedriusS Thank you for your reminder. We'll add a license to this repo soon.

**Comment by tennix** [comment]
Fixed by #9
